version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Library
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    restart: on-failure
    build:
      context: ./Library
      dockerfile: Dockerfile
    ports:
      - "7000:8080"
      - "7001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=Library;Username=postgres;Password=postgres
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: ./library-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
    driver: local
